books = [
    {
        "id": 1,
        "title": "Python Basics",
        "author": "Mark Lutz",
        "year": 2018,
        "pages": 500,
    },
    {
        "id": 2,
        "title": "Clean Code",
        "author": "Robert Martin",
        "year": 2008,
        "pages": 464,
    },
    {
        "id": 3,
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "year": 2019,
        "pages": 302,
    },
    {
        "id": 4,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "year": 2022,
        "pages": 1014,
    },
    {
        "id": 5,
        "title": "Learning Python",
        "author": "Mark Lutz",
        "year": 2013,
        "pages": 1648,
    },
    {
        "id": 6,
        "title": "Python Cookbook",
        "author": "David Beazley",
        "year": 2019,
        "pages": 706,
    },
    {
        "id": 7,
        "title": "Automate the Boring Stuff",
        "author": "Al Sweigart",
        "year": 2020,
        "pages": 504,
    },
    {
        "id": 8,
        "title": "Think Python",
        "author": "Allen Downey",
        "year": 2015,
        "pages": 274,
    },
]
