books = [
    {
        "id": 1,
        "title": "Python Basics",
        "author": "Mark Lutz",
        "year": 2020,
        "pages": 750,
    },
    {
        "id": 2,
        "title": "Clean Code",
        "author": "Robert Martin",
        "year": 2008,
        "pages": 464,
    },
    {
        "id": 3,
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "year": 2019,
        "pages": 360,
    },
    {
        "id": 4,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "year": 2022,
        "pages": 1014,
    },
    {
        "id": 5,
        "title": "The Pragmatic Programmer",
        "author": "David Thomas",
        "year": 2019,
        "pages": 352,
    },
    {
        "id": 6,
        "title": "Learning Python",
        "author": "Mark Lutz",
        "year": 2013,
        "pages": 1648,
    },
    {
        "id": 7,
        "title": "Python Tricks",
        "author": "Dan Bader",
        "year": 2017,
        "pages": 302,
    },
    {
        "id": 8,
        "title": "Automate the Boring Stuff",
        "author": "Al Sweigart",
        "year": 2019,
        "pages": 504,
    },
]