books = [
    {
        "id": 1,
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "year": 1937,
        "pages": 310,
    },
    {
        "id": 2,
        "title": "1984",
        "author": "George Orwell",
        "year": 1949,
        "pages": 328,
    },
    {
        "id": 3,
        "title": "Animal Farm",
        "author": "George Orwell",
        "year": 1945,
        "pages": 112,
    },
    {
        "id": 4,
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "year": 1813,
        "pages": 432,
    },
    {
        "id": 5,
        "title": "Emma",
        "author": "Jane Austen",
        "year": 1815,
        "pages": 474,
    },
    {
        "id": 6,
        "title": "Harry Potter and the Philosopher's Stone",
        "author": "J.K. Rowling",
        "year": 1997,
        "pages": 223,
    },
    {
        "id": 7,
        "title": "Harry Potter and the Chamber of Secrets",
        "author": "J.K. Rowling",
        "year": 1998,
        "pages": 251,
    },
    {
        "id": 8,
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "year": 1925,
        "pages": 180,
    },
    {
        "id": 9,
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "year": 1960,
        "pages": 336,
    },
    {
        "id": 10,
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "year": 1951,
        "pages": 277,
    },
    {
        "id": 11,
        "title": "Fahrenheit 451",
        "author": "Ray Bradbury",
        "year": 1953,
        "pages": 256,
    },
    {
        "id": 12,
        "title": "The Little Prince",
        "author": "Antoine de Saint-Exupery",
        "year": 1943,
        "pages": 96,
    },
]