[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "lab-02"
version = "1.0.0"
description = "Lab 02 - Data Structures and Functional Decomposition"
requires-python = ">=3.10"

[tool.pytest.ini_options]
pythonpath = [
    "."
]

testpaths = [
    "tests"
]
